### ISSUE TITLE
Миксины

### ISSUE THREAD

**Issue by Frolikow** [Nelliza/resume#1]
+ Каждый миксин - это должен быть 1 блок.
+ Имя миксина, имя блока, имя файла в котором миксин - должно быть одинаковым. 
+ Файлы с символом нижнего подчеркивания, можно писать без нижнего подчеркивания.
+ Все миксины должны быть на одном уровне в папке blocks(например). 

upd.
При именовании, так же нужно придерживаться одного стиля. Если у тебя файл, например,  contact-list, то внутри миксин должен быть миксин contact-list, а не contactList

**Comment by Frolikow** [comment]
В блоках` skills-item, software-item` нету блока. Миксин возвращает элемент
Объясни плиз один момент. У тебя есть папка `subtitle-icon`, это по логике должен быть блок, ведь лежит в папке "компоненты". Но внутри только стили, для модификатора блока `subtitle`. Почему так сделано?)

**Comment by Frolikow** [comment]
И еще, основные блоки на макете, почему они не миксинами реализованы?

**Comment by Nelliza** [comment]
> В блоках` skills-item, software-item` нету блока. Миксин возвращает элемент
Вот здесь кажется поняла тебя - мне нужно div, возвращаемый миксином, вместо элемента родительского блока (.skills__item) сделать самостоятельным блоком (.skills-item), так ведь?

> Объясни плиз один момент. У тебя есть папка `subtitle-icon`, это по логике должен быть блок, ведь лежит в папке "компоненты". Но внутри только стили, для модификатора блока `subtitle`. Почему так сделано?)
> папки `size` `linear-gradient` `font-face` `colors` `animate-stripes`, тоже к этому вопросу относятся) это все точно компоненты?)
Этот вопрос тоже меня мучает - это всё scss-миксины (кроме colors), причем если первый (subtitle-icon) используется только одним из блоков, то остальные - одновременно несколькими блоками. Я по аналогии с pug-миксинами думала, что их нужно выносить отдельно в качестве компонентов. Понимаю, что это не совсем компоненты, но вот куда их деть, не могу придумать )

**Comment by Nelliza** [comment]
> И еще, основные блоки на макете, почему они не миксинами реализованы?

Потому что они не принимают никаких параметров. Но сейчас я вижу логику реализации их через миксины, если исходить из правила: 1 миксин = 1 блок. Без проблем, переделаю )
